apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: data-grid
  namespace: data-grid
spec:
  targetNamespaces:
    - data-grid
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datagrid
  namespace: data-grid
spec:
  channel: 8.1.x
  installPlanApproval: Automatic
  name: datagrid
  source: redhat-operators
  sourceNamespace: openshift-marketplace